version: "2"
services:
    brain:
        image: openag/rpi_brain
        expose:
            - 5000
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
        command: ~/catkin_ws/devel/env.sh rosrun openag_brain main personal_food_computer_v2.launch -D http://db:5984 -A http://brain:5000 --screen
        depends_on:
            - db
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
    db:
        image: dogi/rpi-couchdb
        expose:
            - 5984
        ports:
            - 5984:5984
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
